services:
  DB-KIMAI:
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=kimai_db
      - MYSQL_USER=kimai_user
      - MYSQL_PASSWORD=kimai_password
      - MYSQL_ROOT_PASSWORD=kimai_root_password
    networks:
      - CONNECT
    volumes:
      - KIMAI-DB-VOL:/var/lib/mysql

  KIMAI:
    image: kimai/kimai2:apache
    ports:
      - "80:8001"
    environment:
      - DATABASE_URL=mysql://kimai_user:kimai_password@DB-KIMAI:3306/kimai_db
    networks:
      - CONNECT
    depends_on:
      - DB-KIMAI

volumes:
  KIMAI-DB-VOL:

networks:
  CONNECT: {}
